name: CI
on:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run tests and collect coverage
        run: |
          npm ci
          npm run test
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./coverage/coverage-final.json
          flags: unittest
